#!/usr/bin/env bash
#
# Run the record level measure of language features
#
# Input
#   The json files take place on HDFS /europeana directory
# Output
#   You should specify a file name, such as resultXX-language.csv
#   This will be the input of top level, and collection level aggregations

OUTPUT=$1
SKIP_ENRICHMENTS_FLAG=$2
EXTFIELD_EXTRACTION_FLAG=$3
JAR_VERSION=0.6-SNAPSHOT
HDFS=hdfs://localhost:54310
HEADER=header-multilingual-saturation.csv
HEADEROUTPUT=/join/$HEADER
HEADERCRC=.$HEADER.crc

if [[ ("$#" -ne 1 && "$#" -ne 2 && "$#" -ne 3) || ("$OUTPUT" == "") ]]; then
  echo "You should add an output file (such as resultXX-multilingual-saturation.csv)!"
  exit 1
fi

if [ -e $OUTPUT ]; then
  echo "WARNING! $OUTPUT exists, rename it to prevent overwriting the file!"
  exit 1
fi

if [[ ("$SKIP_ENRICHMENTS_FLAG" != "--skipEnrichments" && "$SKIP_ENRICHMENTS_FLAG" != "-s") ]]; then
  SKIP_ENRICHMENTS_FLAG=""
fi

if [[ ("$EXTFIELD_EXTRACTION_FLAG" != "--extendedFieldExtraction") ]]; then
  EXTFIELD_EXTRACTION_FLAG=""
fi

FORMAT="fullbean"

echo "Starting multilingual saturation detection."

if hdfs dfs -test -d /result; then
  hdfs dfs -rm -r -f -skipTrash /result
  sleep 5
fi

if hdfs dfs -test -d $HEADEROUTPUT; then
  hdfs dfs -rm -r -f -skipTrash $HEADEROUTPUT
  sleep 2
fi

JAR=target/europeana-qa-spark-${JAR_VERSION}-jar-with-dependencies.jar
#  --inputFileName /projects/pkiraly/2018-03-23/full/\*.json \
#  --inputFileName $HDFS/europeana/*.json \
#  --inputFileName $HDFS/europeana/*.json.gz \

spark-submit --class de.gwdg.europeanaqa.spark.MultilingualSaturation \
  --master local[*] \
  $JAR \
  --inputFileName $HDFS/europeana/*.json.gz \
  --outputFileName $HDFS/result \
  --headerOutputFile $HDFS$HEADEROUTPUT \
  --dataProvidersFile data-providers.txt \
  --datasetsFile datasets.txt \
  --format $FORMAT \
  $SKIP_ENRICHMENTS_FLAG $EXTFIELD_EXTRACTION_FLAG

echo Retrieve $OUTPUT
hdfs dfs -getmerge /result $OUTPUT
rm .$OUTPUT.crc

echo Retrieve $HEADER
hdfs dfs -getmerge $HEADEROUTPUT $HEADER
sleep 2
rm -f $HEADERCRC

if hdfs dfs -test -d $HEADEROUTPUT; then
  hdfs dfs -rm -r -f -skipTrash $HEADEROUTPUT
  sleep 2
fi

date +"%T"
echo "Multilingual saturation detection is done!"
