#!/usr/bin/env bash

TARGET_CSV=result14-language.csv

echo "Starting language detection."

if [ -e $TARGET_CSV ]; then
  echo "WARNING! $TARGET_CSV exists, rename it to prevent overwriting the file!"
  exit
fi

hdfs dfs -rm -r -skipTrash /result
wait 5
JAR=target/europeana-qa-spark-0.4-SNAPSHOT-jar-with-dependencies.jar

spark-submit --class de.gwdg.europeanaqa.spark.LanguageCount \
  --master local[*] $JAR \
  hdfs://localhost:54310/europeana/*.json \
  hdfs://localhost:54310/result \
  data-providers.txt \
  datasets.txt

hdfs dfs -getmerge /result $TARGET_CSV
rm .$TARGET_CSV.crc

echo "Language detection done."
