#!/usr/bin/env bash

TARGET_CSV=result14.csv
JAR_VERSION=0.4-SNAPSHOT

echo "Run completeness count"

if [ -e $TARGET_CSV ]; then
  echo "WARNING! $TARGET_CSV exists, rename it to prevent overwriting the file!"
  exit
fi

hdfs dfs -rm -r -skipTrash /result
wait 5
spark-submit --class de.gwdg.europeanaqa.spark.CompletenessCount \
  --master local[*] target/europeana-qa-spark-${JAR_VERSION}-jar-with-dependencies.jar \
  hdfs://localhost:54310/europeana/*.json \
  hdfs://localhost:54310/result \
  data-providers.txt \
  datasets.txt

hdfs dfs -getmerge /result $TARGET_CSV
rm .$TARGET_CSV.crc

echo "Completeness count is done!"
